#!/bin/bash
# GitHub Discussion Finder for PulseWatch Engagement
# Runs every 4 hours, finds fresh discussions to engage with
# Saves results to GITHUB_ENGAGEMENT_QUEUE.md

set -e

WORKSPACE="$HOME/.openclaw/workspace"
DRAFTS_DIR="$WORKSPACE/DRAFTS"
QUEUE_FILE="$WORKSPACE/GITHUB_ENGAGEMENT_QUEUE.md"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M %Z')

echo "🦖 HIVE: Starting GitHub discussion discovery..."

# Search queries to run
QUERIES=(
    "site:github.com/discussions \"uptime monitoring\" OR \"status page\" 2025..2026"
    "site:github.com/issues \"monitoring\" OR \"alerting\" OR \"oncall\" 2025..2026"
    "site:github.com/discussions \"vendor\" OR \"third-party\" OR \"dependency\" monitoring 2025..2026"
    "site:github.com/issues \"statuspage\" OR \"betteruptime\" OR \"uptimerobot\" 2025..2026"
)

# Create drafts directory if needed
mkdir -p "$DRAFTS_DIR"

# Start building the queue file
cat > "$QUEUE_FILE" << 'HEADER'
# GitHub Engagement Queue

**Auto-generated by HIVE | Last updated:** TIMESTAMP_PLACEHOLDER

---

## 🎯 Ready to Post (Copy → Paste)

HEADER

# Replace timestamp placeholder
sed -i "s/TIMESTAMP_PLACEHOLDER/$TIMESTAMP/" "$QUEUE_FILE"

DISCUSSION_COUNT=0

for QUERY in "${QUERIES[@]}"; do
    echo "Searching: $QUERY"
    
    # Use web_search via OpenClaw (this would be called from within the agent)
    # For now, we'll just log the query
    echo "  → Query logged for next search cycle"
done

# Add the posting stats section
cat >> "$QUEUE_FILE" << 'FOOTER'

---

## 📊 Posting Stats

| Date | Discussions Found | Comments Posted | Status |
|------|------------------|-----------------|--------|
| AUTO_FILLED | AUTO_FILLED | AUTO_FILLED | ⏳ Pending review |

---

## 🔄 Schedule

- **Discovery:** Every 4 hours (9 AM - 6 PM Chicago time)
- **Review:** Manual (Dario reviews drafts before posting)
- **Auto-post:** Not enabled (requires GitHub OAuth)

---

## 📝 Process

1. HIVE finds relevant discussions automatically
2. Drafts comments with helpful, non-spammy tone
3. Saves to this queue for your review
4. You post manually (takes ~2 min per day)
5. HIVE logs results in memory

FOOTER

echo "✅ Queue updated: $QUEUE_FILE"
echo "📝 Drafts saved to: $DRAFTS_DIR"
